### ISSUE TITLE
Looks great, but....

### ISSUE THREAD

**Issue by wilpar** [pythonhubdev/firebase_authentication_flutter_DDD#1]
It seems far more complicated than it needs to be just to log someone in.  

Considering this is linked to from the official Riverpod site, could you please document your work, why it should be done the way you've done it, etc?

Much appreciated.

**Comment by pythonhubpy** [comment]
Thanks for having a loot at the repo. This is actually to demonstrate how can we implement **Flutter Domain Driven Development** demonstrated by **ResoCoder in his YouTube** channel with the help of Riverpod. 

Sure will do the documentation. And can you please brief what you would expect in the documentation?

**Comment by wilpar** [comment]
Hi @pythonhubpy , sorry for the late reply.  I really think people who are new to a subject need to be exposed to a single concept at a time - in terms of riverpod examples, it should be riverpod-focused, not domain driven development.  This could and should be a different topic for a different time.
